[general]
import = ["/home/pacfrog/.config/alacritty/themes/catppuccin_mocha.toml"]

[terminal.shell]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[window]
decorations = "Full"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9

[mouse]
hide_when_typing = true
